version: '3'
services:
  frontend:
    image: villeve/vegeta_frontend:latest
    ports:
      - "5000:80"
    expose:
      - "5000"
      - "80"
    networks:
      - webnet
    depends_on:
      - backend
  backend:
    build: .
    expose:
     - "8081"
    ports:
      - "8081:8081"
    networks:
      - webnet
    environment:
      DB_HOST: db
    depends_on:
      - db
  db:
    image: postgres
    user: postgres
    networks:
      - webnet
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: node
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  nginx:
      image: nginx
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      networks:
        - webnet
  
networks:
  webnet: